### ISSUE TITLE
Adding the file about the Bnf Rés. J-845 document (Ancient French)

### ISSUE THREAD

**Issue by apogonoe** [HN-2021-Boccacius/git-project-Boccace#16]
Adding of the first subfolder presenting the models of the project. 

You can find in this folder the following elements : 

- A .jpg showing the accuracy of each model made on escriptorium.
- A segmentation model
- A first transcription model accurate at about 94%. It was made by using the entire initial sample of twenty pages of training. 
- A second transcription model, more accurate and that is the result of only 16 pages of the initial sample.

**Comment by apogonoe** [comment]
Update : 

Due to git problems, I only pushed the models, not the .jpg document. It will soon be added.

**Comment by malamatenia** [comment]
OK, we continue at the same time with the definition of norms and the update of our respective folders, with the transcription, pdfs and XML ALTO versions.
