### ISSUE TITLE
LaTeX document

### ISSUE THREAD

**Issue by apogonoe** [HN-2021-Boccacius/git-project-Boccace#18]
Matenia, would it be possible to push the LaTeX document on the first page of the repository so that it's easier to find and modify? Thx _

**Comment by malamatenia** [comment]
Yes, I am on it. I am commenting here the link to edit the document on OverLeaf, and I am uploading the document .tex on the repository as a first draft to review by Marco or any external spectator. 

The link for editing is :
https://www.overleaf.com/1347212823bjdzxggwnknq
and for mere visualisation :
https://www.overleaf.com/read/dpgwmqnxhrdh

**Comment by malamatenia** [comment]
Closing the issue as it was resolved. cf. LaTeX_documentation folder.
